
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wardani
 */
public class Nilai extends javax.swing.JFrame {

    public Nilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmdsave = new javax.swing.JButton();
        cmdupdate = new javax.swing.JButton();
        cmddelete = new javax.swing.JButton();
        cmdcancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmakul = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbonilai = new javax.swing.JComboBox<>();
        cbonim = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tnilai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATA NILAI MATA KULIAH");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmdsave.setText("SAVE");
        cmdsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsaveActionPerformed(evt);
            }
        });

        cmdupdate.setText("UPDATE");
        cmdupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdupdateActionPerformed(evt);
            }
        });

        cmddelete.setText("DELETE");
        cmddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeleteActionPerformed(evt);
            }
        });

        cmdcancel.setText("CANCEL");
        cmdcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelActionPerformed(evt);
            }
        });

        jLabel4.setText("NIM");

        jLabel3.setText("NAMA");

        jLabel5.setText("MAKUL");

        jLabel6.setText("NILAI");

        cbonilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));

        cbonim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbonim.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbonimPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdsave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(cmdupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmddelete))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(53, 53, 53)
                                .addComponent(cbonim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(cmdcancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbonilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmakul, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbonim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmakul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbonilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsave)
                    .addComponent(cmdupdate)
                    .addComponent(cmddelete)
                    .addComponent(cmdcancel))
                .addContainerGap())
        );

        jLabel9.setText("SEARCH");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        tnilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tnilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tnilaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tnilai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     Nama : Eggy Andika Wardani
     NIM  : 20185102
    Kelas : 5E
     */
    String koneksi ="jdbc:mysql://localhost/dbakademik";
    String user ="root";
    String pass ="";
    Connection connection;
    Statement statement;
    private void cmdsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsaveActionPerformed
        try {
            String sql;
            {
                sql = "insert into nilaimakul values('";
                sql+= cbonim.getSelectedItem()+"','";
                sql+= txtmakul.getText()+"','";
                sql+= cbonilai.getSelectedItem()+"')";
            }
            
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Simpan data berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Simpan data gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error: "+ DBException);
        }
        bersih();
        loaddata();
            
    }//GEN-LAST:event_cmdsaveActionPerformed

    private void cmdupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdupdateActionPerformed
        try {
            String sql;
            {
                sql = "update nilaimakul set makul='";
                sql+= txtmakul.getText()+"',nilai='";
                sql+= cbonilai.getSelectedItem()+ "'";
                sql+= "where nim='" + cbonim.getSelectedItem()+"'";
                
            }
            
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Update data berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Update data gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error: "+ DBException);
            
        }
        bersih();
        loaddata();
        cbonim.setEditable(true);
        txtnama.setEditable(false);
        cmdsave.setEnabled(true);
        cmdupdate.setEnabled(false);
        cmddelete.setEnabled(false);
    }//GEN-LAST:event_cmdupdateActionPerformed

    private void cmddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeleteActionPerformed
        try {
            int reply = JOptionPane.showConfirmDialog(this, "Apakah anda yakin menghapus data ini?","Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                String sql = "delete from nilaimakul where nim='" + cbonim.getSelectedItem() +"'";
                statement.executeUpdate(sql);
            }
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Hapus data gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error: "+ DBException);
        }
        bersih();
        loaddata();
        cmdupdate.setEnabled(false);
        cmddelete.setEnabled(false);
        cmdsave.setEnabled(true);
        cbonim.setEditable(false);
    }//GEN-LAST:event_cmddeleteActionPerformed

    private void cmdcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelActionPerformed
        dispose();
    }//GEN-LAST:event_cmdcancelActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("NIM");
        tabel.addColumn("NAMA");
        tabel.addColumn("MATA KULIAH");
        tabel.addColumn("NILAI");
        
        try {
            String sql = "select * from mahasiswa where nim like '%" + txtcari.getText()+ "%'"+ "or nama like '%" + txtcari.getText() +"%'";
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4)
    
            });
            }
            tnilai.setModel(tabel);
        } catch (Exception DBException) {
            System.err.println("Error "+ DBException);
        }

    }//GEN-LAST:event_txtcariKeyPressed

    private void tnilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnilaiMouseClicked
        cbonim.setSelectedItem(tnilai.getValueAt(tnilai.getSelectedRow(), 0).toString());
        txtnama.setText(tnilai.getValueAt(tnilai.getSelectedRow(), 1).toString());
        txtmakul.setText(tnilai.getValueAt(tnilai.getSelectedRow(), 2).toString());
        cbonilai.setSelectedItem(tnilai.getValueAt(tnilai.getSelectedRow(), 3).toString());
        cmdupdate.setEnabled(true);
        cmddelete.setEnabled(true);
        cbonim.setEditable(false);
        txtnama.setEditable(false);
        cmdsave.setEnabled(false);

    }//GEN-LAST:event_tnilaiMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi= "jdbc:mysql://localhost/dbakademik";
            connection = (Connection) DriverManager.getConnection(koneksi, user, pass);
            statement = (Statement) connection.createStatement();
            
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal", "error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error : " + DBException);
        }
        bersih();
        loaddata();
    }//GEN-LAST:event_formWindowOpened

    private void cbonimPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbonimPopupMenuWillBecomeInvisible
        try {
            String sql = "select nama from mahasiswa where nim ='"+ cbonim.getSelectedItem()+"'";
            ResultSet rs = statement.executeQuery(sql);
            
            while (rs.next()) {    
                String data = rs.getString("nama");
                txtnama.setText(data);
            }
            
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_cbonimPopupMenuWillBecomeInvisible

    private void bersih() {
        txtmakul.setText("");
        cbonilai.setSelectedIndex(0);
        
        try {
            String sql = "select mahasiswa.nim, mahasiswa.nama, nilaimakul.makul, nilaimakul.nilai "+
                    "from mahasiswa, nilaimakul where mahasiswa.nim = nilaimakul.nim";
            ResultSet rs= statement.executeQuery(sql);
            final String[] header = {"NIM", "NAMA", "MAKUL", "NILAI"};
            rs.last();
            int n = rs.getRow();
            Object[][] data = new Object[n][4];
            int p=0;
            rs.beforeFirst();
            while (rs.next()) {
                data[p][0]=rs.getString(1);
                data[p][1]=rs.getString(2);
                data[p][2]=rs.getString(3);
                data[p][3]=rs.getString(4);
                p++;
                
            }
            tnilai.setModel(new DefaultTableModel(data, header));
            tnilai.setAlignmentX(CENTER_ALIGNMENT);
            
        } catch (Exception DBException) {
            System.err.println("Error" + DBException);
        }
    }

    private void loaddata() {
        try {
            cbonim.removeAllItems();
            String sql = "select * from mahasiswa";
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {  
                cbonim.addItem(rs.getString("nim"));
                
            }
            
        } catch (SQLException e) {
            System.err.println("Terjadi Kesalahan" + e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbonilai;
    private javax.swing.JComboBox<String> cbonim;
    private javax.swing.JButton cmdcancel;
    private javax.swing.JButton cmddelete;
    private javax.swing.JButton cmdsave;
    private javax.swing.JButton cmdupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tnilai;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtmakul;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

    
}

